name: Kamke ODE Test Suite

on:
  push:
    branches:
        - master

jobs:
  test-suite:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Run script
      run: |
        python test_kamke.py --verify --all_hints

    - name: Commit files
      run: |
        bash ./commit.sh
    # - name: Push changes  # push the output folder to your repo
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.API_TOKEN }}
    #     force: true