name: Kamke ODE Test Suite

on:
  push

jobs:
  generate-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [1, 2]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Chapter ${{ matrix.node }}
        run: |
          python test_kamke.py -ch ${{ matrix.node }}

      - uses: actions/upload-artifact@v2
        with:
          name: chapter_${{ matrix.node }}
          path: json/chapter_${{ matrix.node }}

  generate-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - uses: actions/download-artifact@v2
        with:
          path: json

      - name: Generate HTML files
        run: |
          python test_kamke.py --html
      
      - name: Commit Files
        run: |
          bash ./commit.sh
